.import FamiToneInit
.import FamiToneSfxInit
.import FamiToneUpdate
.import FamiToneMusicPlay
.import FamiToneMusicStop
.import FamiToneMusicPause
.import FamiToneSfxPlay
.import FamiToneSamplePlay
.import music_data
.import sfx_data
