SPRITE_0_TILE = $07

HUD_HEART_TILE = $25

HUD_FACE_LEFT_TILE = $49
HUD_FACE_RIGHT_TILE = $4b

DIRTY_SINK_TILE_0 = $af
DIRTY_SINK_TILE_1 = $b1

UTENSILS_TILE_LEFT  = $b3
UTENSILS_TILE_RIGHT = $b5

GUNK_DROP_0_TILE = $b7
GUNK_DROP_1_TILE = GUNK_DROP_0_TILE + 2
GUNK_DROP_2_TILE = GUNK_DROP_0_TILE + 4

SPLOOSH_ANIMATE_1_TILE = $bd
SPLOOSH_ANIMATE_2_TILE = SPLOOSH_ANIMATE_1_TILE + 2
SPLOOSH_ANIMATE_3_TILE = SPLOOSH_ANIMATE_1_TILE + 4

DIRTY_PILE_TILE_0 = $c3
DIRTY_PILE_TILE_1 = $c5

BROOM_TOP_TILE       = $c7
BROOM_MIDDLE_TILE    = BROOM_TOP_TILE + 2
BROOM_GLOW_A_TILE    = BROOM_TOP_TILE + 4
BROOM_GLOW_B_TILE    = BROOM_TOP_TILE + 6
BROOM_GLOW_C_TILE    = BROOM_TOP_TILE + 8
BROOM_MOP_LEFT_TILE  = BROOM_TOP_TILE + 10
BROOM_MOP_RIGHT_TILE = BROOM_TOP_TILE + 12

TOASTER_SIT_TILE = $d5
TOASTER_JUMP0_TILE = TOASTER_SIT_TILE + $0c
TOASTER_JUMP1_TILE = TOASTER_SIT_TILE + $10
ELEC_JUMP1_TILE    = TOASTER_SIT_TILE + $04
TOASTER_JUMP2_TILE = TOASTER_SIT_TILE + $14
ELEC_JUMP2_TILE    = TOASTER_SIT_TILE + $08

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SPRITE_0_FOR_BOSS_TILE = $af

DIRTY_SPIT_TILE_0 = $b1
DIRTY_SPIT_TILE_1 = DIRTY_SPIT_TILE_0 + 2

BOSS_HEALTH_EDGE_TILE = $b5
BOSS_HEALTH_METER_BASE_TILE = BOSS_HEALTH_EDGE_TILE + 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

STAR_ANIMATE_0_TILE = $b1
STAR_ANIMATE_1_TILE = STAR_ANIMATE_0_TILE + 2
STAR_ANIMATE_2_TILE = STAR_ANIMATE_0_TILE + 4

