HUD_HEART_TILE = $2b

HUD_FACE_LEFT_TILE = $45
HUD_FACE_RIGHT_TILE = $47

DIRTY_SINK_TILE_0 = $a1
DIRTY_SINK_TILE_1 = $a3

UTENSILS_TILE_LEFT  = $a5
UTENSILS_TILE_RIGHT = $a7

GUNK_DROP_0_TILE = $a9
GUNK_DROP_1_TILE = $ab
GUNK_DROP_2_TILE = $ad

SPLOOSH_ANIMATE_1_TILE = $af
SPLOOSH_ANIMATE_2_TILE = $b1
SPLOOSH_ANIMATE_3_TILE = $b3

DIRTY_PILE_TILE_0 = $b5
DIRTY_PILE_TILE_1 = $b7

BROOM_TOP_TILE       = $b9
BROOM_MIDDLE_TILE    = BROOM_TOP_TILE + 2
BROOM_GLOW_A_TILE    = BROOM_TOP_TILE + 4
BROOM_GLOW_B_TILE    = BROOM_TOP_TILE + 6
BROOM_GLOW_C_TILE    = BROOM_TOP_TILE + 8
BROOM_MOP_LEFT_TILE  = BROOM_TOP_TILE + 10
BROOM_MOP_RIGHT_TILE = BROOM_TOP_TILE + 12

STAR_ANIMATE_0_TILE = $c7
STAR_ANIMATE_1_TILE = STAR_ANIMATE_0_TILE + 2
STAR_ANIMATE_2_TILE = STAR_ANIMATE_0_TILE + 4

SPRITE_0_TILE = $cd

TOASTER_SIT_TILE = $cf
TOASTER_JUMP0_TILE = TOASTER_SIT_TILE + $0c
TOASTER_JUMP1_TILE = TOASTER_SIT_TILE + $10
ELEC_JUMP1_TILE    = TOASTER_SIT_TILE + $04
TOASTER_JUMP2_TILE = TOASTER_SIT_TILE + $14
ELEC_JUMP2_TILE    = TOASTER_SIT_TILE + $08

DIRTY_SPIT_TILE_0 = $e7
DIRTY_SPIT_TILE_1 = $e9

BOSS_HEALTH_EDGE_TILE = $eb
BOSS_HEALTH_METER_BASE_TILE = $ed
