.import MemoryLayoutInit
.import MemoryLayoutFillChrRam

MEMORY_LAYOUT_BANK_GAMEPLAY_CHR = 0
MEMORY_LAYOUT_BANK_SCREEN_CHR = 1
MEMORY_LAYOUT_BANK_MAIN_CODE = 2

MEMORY_LAYOUT_NORMAL_POINTER = $80
MEMORY_LAYOUT_BOSS_POINTER = $a0
