.import MsgRender
.importzp MSG_HEALTH, MSG_LIVES, MSG_SCORE, MSG_COMBO
.importzp MSG_ZERO_SCORE, MSG_ZERO_COMBO, MSG_PRESS, MSG_START
.importzp MSG_THE_KITCHEN_IS
.importzp MSG_FIND_THE_BROOM
.importzp MSG_AND_CLEAN_IT_UP
.importzp MSG_KILL_ALL_THE_FLIES
.importzp MSG_WATCH_OUT_FOR
.importzp MSG_AND_APPLIANCES
.importzp MSG_KEEP_GOING_ALMOST
.importzp MSG_GET_COMBO_KILLS
.importzp MSG_TO_EARN_HIGH
.importzp MSG_WARNING
.importzp MSG_BOSS_FLY_IS_APPROACHING
.importzp MSG_RESOLVE_YOUR_BATTLE
.importzp MSG_YOU_DID_IT
.importzp MSG_THE_KITCHEN_IS_CLEAN
.importzp MSG_SELECT_LEVEL
.importzp MSG_COPYRIGHT
.importzp MSG_MARQUE_LEVEL
.importzp MSG_MARQUE_LIVES
.importzp MSG_DEMO
