.import MsgRender
.importzp MSG_HEALTH, MSG_LIVES, MSG_SCORE, MSG_COMBO
.importzp MSG_ZERO_SCORE, MSG_ZERO_COMBO, MSG_PRESS, MSG_START
.importzp MSG_THE_KITCHEN_IS_FILTHY
.importzp MSG_FIND_THE_BROOM
